- .github/workflows/rust-unit.yml
- Cargo.lock
- sdk/Cargo.toml
- ydb-grpc/Cargo.toml
> add rust cache

- README.md
- ydb/README.md
- ydb/src/lib.rs
> rename to YDB

- CONTRIBUTING.md
No behavior changes 
Add contributing description
> add contributing description

- .github/workflows/publish-crate.yml
- .github/workflows/rust-unit.yml
- README.md
- ydb/README.md
- ydb/src/credentials.rs
run tests with default rust version
Run tests with fixed rust version
> Run tests with fixed rust version

- .github/workflows/rust-tests.yml
Run only unit tests
Run unit and integration tests with ydb docker container
> Run integration tests with ydb docker container

- .github/workflows/rust-tests.yml
> run ignored (integration) tests

- .github/workflows/rust-tests.yml
- README.md
Tests run only on pr.
Additinal scheduled run tests. It allow detect if test env fail without change code.
> add scheduled daily tests

- ydb/src/client_table_test_integration.rs
While test stream read current test check about result has more then one result set, but it isn't guranteed for test data.
Doesn't check result sets count
> Remove flapped test assert

- .github/scripts/wait-ydb-container.sh
- .github/workflows/rust-tests.yml
move wait container code from raw command to script
> wait ydb container as script

- Cargo.lock
- ydb/Cargo.toml
> Use rustls for metadata requwest instead of native-tls

- ydb/src/client.rs
- ydb/src/client_directory.rs
- ydb/src/client_directory_test_integration.rs
- ydb/src/client_table_test_integration.rs
- ydb/src/discovery.rs
- ydb/src/lib.rs
- ydb/src/test_integration_helper.rs
- ydb/src/trait_operation.rs
> Support directories operations.

- ydb/src/client_builder.rs
parse arg token in connection string
> add token arg to connection string

- ydb/src/channel_pool.rs
- ydb/src/client_builder.rs
- ydb/src/client_directory.rs
- ydb/src/client_table.rs
- ydb/src/connection_pool.rs
- ydb/src/discovery.rs
- ydb/src/grpc_connection_manager.rs
- ydb/src/grpc_wrapper/grpc_discovery_client.rs
- ydb/src/grpc_wrapper/grpc_services.rs
- ydb/src/grpc_wrapper/mod.rs
- ydb/src/lib.rs
- ydb/src/load_balancer.rs
create single point for create grpc services with auth
> Add grpc_connection_manager

- .github/scripts/version-up.sh
- Cargo.lock
- ydb-grpc-helpers/Cargo.toml
- ydb-grpc/Cargo.toml
> fix find syntax for linux

- .github/scripts/version-up.sh
> show git diff before set tag

- ydb/src/client_table_test_integration.rs
…ile compile code
Disable trace for test, generated a lot of logs
> disable trace for test with a lot of logging

- Cargo.lock
- ydb-grpc-helpers/Cargo.toml
- ydb-grpc/Cargo.toml
> bump version for ydb-grpc-helpers, patch

- ydb/src/client_scheme/client.rs
- ydb/src/grpc_wrapper/macroses.rs
- ydb/src/grpc_wrapper/mod.rs
- ydb/src/grpc_wrapper/raw_scheme_client/client.rs
- ydb/src/grpc_wrapper/raw_table_service/client.rs
- ydb/src/grpc_wrapper/raw_table_service/create_session.rs
- ydb/src/grpc_wrapper/raw_table_service/mod.rs
- ydb/src/session.rs
- ydb/src/session_pool.rs
Use internal method for ge channel in session instead direct pool usage
> Use macroses for implement raw <-> grpc typos conversations

- .github/scripts/start-ydb-container.sh
> Fix flaky test with empty storage pool

- .github/workflows/rust-tests.yml
- ydb/src/client_table_test_integration.rs
- ydb/src/discovery.rs
- ydb/src/lib.rs
- ydb/src/session.rs
- ydb/src/test_helpers.rs
- ydb/src/test_integration_helper.rs
- ydb/src/trace_helpers.rs
write/read data, guaranteed more then one batch for streaming test - for check about it good
> fix stream test

- .github/workflows/rust-tests.yml
- ydb-grpc/src/lib.rs
- ydb/src/client_scheme/client.rs
- ydb/src/client_table.rs
- ydb/src/credentials.rs
- ydb/src/discovery.rs
- ydb/src/errors.rs
- ydb/src/grpc.rs
- ydb/src/grpc_connection_manager.rs
- ydb/src/grpc_wrapper/channel.rs
- ydb/src/grpc_wrapper/grpc.rs
- ydb/src/load_balancer.rs
- ydb/src/session.rs
- ydb/src/transaction.rs
- ydb/src/types.rs
set rust 1.63.0 for CI and fix new clippy linter warnings
> Update latest rust in CI

- ydb/src/client_builder.rs
- ydb/src/test_helpers.rs
add tests for old and new style parse database (parsing was implementer already)
> add test for parse database in old and new style

- .github/workflows/rust-tests.yml
Use default cache settings (incremental cache enables).
No cache version
Disable incremental cache - it will generate less build cache: faster compile, download and decompress cache.
Add cache version for cache key for emulation of reset cache.
> disable incremental cache

- ydb/src/client.rs
- ydb/src/client_scheme/client.rs
- ydb/src/client_table.rs
- ydb/src/errors.rs
- ydb/src/grpc_wrapper/raw_table_service/client.rs
- ydb/src/grpc_wrapper/raw_ydb_operation.rs
- ydb/src/session.rs
- ydb/src/session_pool.rs
Create session and keep_alive direct with grpc service
Create session and keep_alive direct with raw table client wrapper
> Create session with raw client

- ydb/src/grpc_wrapper/macroses.rs
- ydb/src/grpc_wrapper/raw_scheme_client/client.rs
- ydb/src/grpc_wrapper/raw_table_service/client.rs
- ydb/src/grpc_wrapper/raw_table_service/commit_transaction.rs
- ydb/src/grpc_wrapper/raw_table_service/keepalive.rs
- ydb/src/grpc_wrapper/raw_table_service/mod.rs
- ydb/src/grpc_wrapper/raw_table_service/rollback_transaction.rs
- ydb/src/session.rs
switch commit and rollback transactions for raw client
> Switch commit and rollback transaction for raw client

- ydb/src/grpc.rs
- ydb/src/grpc_wrapper/raw_table_service/client.rs
- ydb/src/grpc_wrapper/raw_table_service/execute_scheme_query.rs
- ydb/src/grpc_wrapper/raw_table_service/mod.rs
- ydb/src/session.rs
scheme query with old direct grpc client
scheme query with raw wrapper
> scheme query with raw client

- README.md
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru
> Fix misspell.

- .github/workflows/publish-crate.yml
- .github/workflows/rust-tests.yml
- ydb/src/client_table.rs
Update latest rust for tests from 1.65 to 1.66
> update latest rust

- ydb/src/types.rs
Publish special method for create list values instead of create direct enums
> publish method list_from

- ydb/src/query.rs
- ydb/src/types.rs
public method for set keep_in_cache flag for query
> Manual keep in cache

- Cargo.lock
- ydb/src/grpc_wrapper/mod.rs
- ydb/src/grpc_wrapper/raw_topic_service/client.rs
- ydb/src/grpc_wrapper/raw_topic_service/common/codecs.rs
- ydb/src/grpc_wrapper/raw_topic_service/common/consumer.rs
- ydb/src/grpc_wrapper/raw_topic_service/common/metering_mode.rs
- ydb/src/grpc_wrapper/raw_topic_service/common/mod.rs
- ydb/src/grpc_wrapper/raw_topic_service/common/partitioning_settings.rs
- ydb/src/grpc_wrapper/raw_topic_service/create_topic.rs
- ydb/src/grpc_wrapper/raw_topic_service/mod.rs
- ydb/src/trait_operation.rs
> feat: create wrapper structs for create topic method

- .github/workflows/publish-crate.yml
- .github/workflows/rust-tests.yml
- Cargo.lock
- ydb/src/grpc_wrapper/raw_table_service/value/type.rs
- ydb/src/grpc_wrapper/raw_table_service/value/value_ydb.rs
> update newest rust to 1.68.0

- .github/workflows/publish-crate.yml
- .github/workflows/rust-tests.yml
- Cargo.lock
- ydb/src/load_balancer.rs
> update rust to 1.70

- .github/workflows/rust-tests.yml
- ydb/src/client_builder.rs
- ydb/src/connection_pool.rs
- ydb/src/errors.rs
send grpc/grpcs scheme to server
send http/https scheme to server
> Fix request scheme bug

- .github/workflows/publish-crate.yml
- .github/workflows/rust-tests.yml
- Cargo.lock
- ydb/src/discovery.rs
- ydb/src/load_balancer.rs
- ydb/src/session_pool.rs
- ydb/src/sugar.rs
- ydb/src/transaction.rs
- ydb/src/waiter.rs
> update rust to 1.72

- ydb/src/result.rs
> impl Send for rows result

- Cargo.lock
- Cargo.toml
> fixed cargo resolver

- .github/workflows/publish-crate.yml
- .github/workflows/rust-tests.yml
> update test newest rust to 1.73

- .github/workflows/rust-tests.yml
no additional build step
-
-
-
> linter after test

- ydb/Cargo.toml
- ydb/README.md
- ydb/src/client.rs
- ydb/src/client_scheme/list_types.rs
- ydb/src/client_topic/topicwriter/message_write_status.rs
- ydb/src/errors.rs
- ydb/src/types.rs
> Add cargo feature disable-non-exhaustive

- ydb/src/client_topic/topicwriter/message_write_status.rs
- ydb/src/client_topic/topicwriter/writer.rs
- ydb/src/client_topic/topicwriter/writer_reception_queue.rs
> Topic writer cosmetic changes in non published api

- ydb/src/errors.rs
can convert YdbOrCustomerError to YdbError
> add to_ydb_error for ydb_or_customer_error

- .github/workflows/publish-crate.yml
- .github/workflows/rust-tests.yml
- ydb/src/client_table_test_integration.rs
> update rust to 1.74

- ydb/src/client_table_test_integration.rs
- ydb/src/grpc_wrapper/raw_table_service/value/type.rs
- ydb/src/grpc_wrapper/raw_table_service/value/value_ydb.rs
- ydb/src/types.rs
- ydb/src/types_converters.rs
> fix yson param

- .github/workflows/rust-tests.yml
- ydb/src/grpc_wrapper/raw_table_service/value/value_ydb_test.rs
> update rust newest rust and linter to 1.75

- .github/workflows/rust-tests.yml
- ydb/Cargo.toml
- ydb/src/auth_test.rs
- ydb/src/client_common.rs
- ydb/src/credentials.rs
- ydb/src/grpc_wrapper/auth.rs
- ydb/src/pub_traits.rs
> hide sensitive strings behind a SecretString

- .github/workflows/rust-tests.yml
> update rust linter

- README.md
- ydb-example-urlshortener/Cargo.toml
- ydb-grpc-helpers/Cargo.toml
- ydb-grpc/Cargo.toml
- ydb/README.md
- ydb/examples/auth-static-credentials.rs
- ydb/src/lib.rs
- ydb/src/test_helpers.rs
> Static Credentials usage example

- Cargo.toml
- ydb-example-urlshortener/Cargo.toml
- ydb-grpc/Cargo.toml
- ydb/Cargo.toml
taplo fmt --option indent_string="    "  Cargo.toml ./ydb/Cargo.toml ./ydb-grpc/Cargo.toml ./ydb-example-urlshortener/Cargo.toml
-
-
-
> reformat Cargo.toml with

- Cargo.lock
- ydb/src/client_table_test_integration.rs
- ydb/src/grpc_wrapper/raw_table_service/value/type.rs
- ydb/src/grpc_wrapper/raw_table_service/value/value_ydb.rs
- ydb/src/types.rs
- ydb/src/types_converters.rs
> Renamed ydb::Value::String -> ydb::Value::Bytes

- Cargo.lock
- ydb/Cargo.toml
Issue Number: #195 
- chrono dependency is now "0.4"
> fix chrono version

- ydb/src/grpc_wrapper/macroses.rs
- ydb/src/grpc_wrapper/raw_auth_service/client.rs
> Fix auth token leakage to the logs

- .github/workflows/slo.yml
slo tests are flaky and have many false positive alerts.
Disable warning of it
> disable slo tests

- .github/workflows/rust-tests.yml
> switch to new ubuntu image

- .github/workflows/rust-tests.yml
> show ydb server version

- Cargo.lock
- ydb-example-urlshortener/src/main.rs
- ydb/examples/auth-env-connection-string.rs
- ydb/examples/auth-static-credentials.rs
- ydb/examples/auth-token.rs
- ydb/examples/auth-yc-cmdline.rs
- ydb/examples/auth-ycloud-metadata.rs
- ydb/examples/auth-ycloud-serviceaccount.rs
- ydb/examples/basic-logs.rs
- ydb/examples/basic-select-upsert.rs
- ydb/examples/basic-upsert-many-rows.rs
- ydb/examples/container-types.rs
- ydb/examples/mutex.rs
- ydb/examples/topic-writer.rs
> add connection timeout to examples

- ydb/src/client_table.rs
> Publish with_error_on_truncate
